Desarrollo/GolGana/GolGana/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from users.urls import post_patterns
from .views import Home, load_cities
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(post_patterns)),
    path('', include('social_django.urls', namespace='social')),
    path('', Home.as_view(), name="home"),
    path('ajax/load-cities', load_cities, name = 'ajax_load_cities'),
    path('', include('canchas.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Desarrollo/GolGana/canchas/urls.py
from django.urls import path
from .views import DetalleReserva, ListaEmpresas, DetalleEmpresa,  VistaAuxReservacion, MisReservaciones, UpdateEmpresa, DeleteCanchas, CrearReserva, CrearCanchas

urlpatterns  = [

path('home/', ListaEmpresas.as_view(), name="home-next"),
path('detalle-cancha/<slug>', DetalleEmpresa.as_view(), name="detalle-cancha"),
path('detalle-reserva/<int:pk>', DetalleReserva.as_view(), name="detalle-reserva"),
path('accounts/cliente/lista-reservas/<slug:slug>', MisReservaciones.as_view(),  name="lista-reservas-cliente"),
path('confirmar-reserva/<int:pk>', VistaAuxReservacion.as_view(), name="vista-reservacion"),
path('update-empresa/<slug>', UpdateEmpresa.as_view(), name='update-empresa'),
path('eliminar-cancha/<int:pk>', DeleteCanchas.as_view(), name='eliminar-cancha'),
path('crear-reserva/', CrearReserva.as_view(), name='crear-reserva'),
path('crear-canchas/', CrearCanchas.as_view(), name='crear-canchas'),
]

Desarrollo/GolGana/users/urls.py
from django.contrib.auth import views
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView, PasswordChangeView

post_patterns = ([
    path('registro/', views.createUserView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('accounts/cliente/<slug:slug>/edit-profile/', views.ProfileClienteUpdate.as_view(), name='edit-profile-cliente'),
    path('accounts/empresa/<slug:slug>/edit-profile/', views.PerfilEmpresaUpdate.as_view(), name='edit-profile-empresa'),
    path('login/', views.CLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    ###AGREGAR QUE SI EL CORREO NO EXISTE NO DEJE ENVIAR PASSWORD RESET
    path('accounts/password-change/', PasswordChangeView.as_view(success_url='/'), name="password-change"),
    path('social/success', views.socialSuccess, name="social-success"),
    path('redirect/account', views.login_redirect, name="login_redirect"),
    path('json/load/cities', views.json_load, name="json-load-cities"),
], "user")

Desarrollo/GolGana/canchas/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from users.models import PerfilEmpresa, PerfilCliente
from users.models import Ciudad, Departamento
from PIL import Image
from django.core.validators import RegexValidator
from django.utils.text import slugify
from datetime import timedelta, date

# Create your models here.

##SE HARIA EN OTRA APP -> APP CANCHAS
#Modelo Empresa.
class Empresa (models.Model):
    #Datos de la empresa.


    nombre = models.CharField(max_length=40, verbose_name="Nombre", default="Nombre Empresa")
    encargado = models.OneToOneField(PerfilEmpresa, on_delete=models.CASCADE)
    descripcion = models.TextField(max_length= 250, verbose_name="Descripcion")
    direccion = models.CharField(max_length=70, verbose_name="Direccion")
    phone_regex = RegexValidator(regex='^(3)([0-9]){9}$', message = "Por favor escribe el numero en el formato aceptado sin código de área ej: 3123456789")
    telefono = models.CharField(validators=[phone_regex], max_length=10, verbose_name="Telefono")
    ciudad = models.ForeignKey(Ciudad, null=True, on_delete=models.SET_NULL, verbose_name="Ciudad")
    departamento = models.ForeignKey(Departamento, null=True, on_delete=models.SET_NULL, verbose_name="Departamento")
    #LATITUD a partir de la direccion con API de google.
    latitud = models.CharField(max_length=50,  verbose_name="Latitud", blank=True, null=True)
    longitud = models.CharField(max_length=50,  verbose_name="Longitud", blank=True, null=True)
    
    #Hora inicial para crear canchas
    hora_inicio = models.TimeField(auto_now_add=False, auto_now=False, null=True)
    #Hora final para crear canchas
    hora_final = models.TimeField(auto_now_add=False, auto_now=False, null=True)


    image = models.ImageField(verbose_name="Imagen", upload_to="media/canchas/image", default="canchas/image/default-image.png")
    slug = models.SlugField(verbose_name="Slug", blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.encargado.pk)+ "-" + slugify(self.nombre)
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        size = (600,300)
        thumb = img.resize(size)
        thumb.save(self.image.path)
    
    def __str__(self) -> str:
        id = str(self.pk)
        return str( id +"-"+ self.nombre)

    def get_jugadores(self):
        empresa = Empresa.objects.get(encargado = self.encargado)
        if Cancha.objects.filter(empresa=empresa):
            jugadores = Cancha.objects.filter(empresa = empresa).values_list('jugadores', flat=True).distinct().order_by('jugadores')
            return jugadores

    def get_reservas(self):
        empresa = Empresa.objects.get(encargado = self.encargado)
        reservas = Reserva.objects.filter(empresa = empresa, date__gte = date.today())
        if reservas:
            return reservas.order_by("date")
            

        

#CANCHAS:
class Cancha(models.Model):
    nombre = models.CharField(max_length=40, verbose_name="Nombre", null=True, blank=True) #Cancha 5
    #Empresa asociada.
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    #Numero de jugadores.
    class NumJugadores(models.IntegerChoices):
        FUTBOL5 = 5, '5'
        FUTBOL6 = 6, '6',
        FUTBOL7 = 7, '7',
        FUTBOL8 = 8, '8',
        FUTBOL9 = 9, '9',
        FUTBOL10 = 10, '10',
        FUTBOL11 = 11, '11'

    jugadores = models.IntegerField( default=NumJugadores.FUTBOL5 , choices=NumJugadores.choices, verbose_name="Numero de jugadores")
    #Si es una cancha pequeña se debe poner a que cancha grande conforma
    cancha_conformada = models.ManyToManyField('self', verbose_name="Canchas que conforman cancha",  blank=True)
    #Imagen.
    image = models.ImageField(verbose_name="Imagen", upload_to="media/canchas/image", default="canchas/image/default-image.png")

    class Meta:
        ordering = ['nombre']

    def save(self, *args, **kwargs):
        super(Cancha, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        size = (600,300)
        thumb = img.resize(size)
        thumb.save(self.image.path)
    
    def __str__(self) -> str:
        return self.nombre

class Reserva(models.Model):
    #Empresa a cargo de la reserva
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, null = True)
    #cancha
    cancha = models.ForeignKey(Cancha, on_delete=models.CASCADE, null=True)
    #Hora y dia
    date = models.DateTimeField(verbose_name= "Fecha y Hora", null=True, auto_now_add=False, auto_now=False)
    #Persona que reservo
    persona = models.ForeignKey(PerfilCliente, on_delete=models.CASCADE, null=True, blank=True)

    #Estado -> Desocupada /  Ya esta activa /confirmando.

    class Estados(models.IntegerChoices):
        DISPONIBLE = 0, 'Disponible'
        POR_CONFIRMAR = 1, 'En confirmacion'
        CONFIRMADA = 2, 'Confirmada'
        CANCELADA = 3, 'Cancelada'
        FINALIZADA = 4, 'Finalizada'

    estado = models.IntegerField(default = Estados.DISPONIBLE, choices = Estados.choices)
    precio = models.FloatField(verbose_name="Precio", default="0")


    def __str__(self):
        return 'Reserva #: ' + str(self.pk)

    def get_hora_final(self):
        return self.date + timedelta(hours=1)

Desarrollo/GolGana/canchas/views.py
from .forms import UpdateEmpresaForm, CrearReserva, CrearCancha
from django.views.generic.edit import CreateView, DeleteView
from users.models import PerfilEmpresa, PerfilCliente, User
from django.urls.base import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from .models import Cancha, Empresa, Reserva
from django.db.models import Q
from datetime import timedelta

# Create your views here.

class ListaEmpresas(LoginRequiredMixin, ListView):
    model = Empresa
    #template de la vista
    template_name = "canchas.html"
    paginate_by = 10
    ordering = "nombre"
    #Aca se listan las empresas 
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        if self.request.method == "GET":
            query = self.request.GET.get("q")
            if query:
                queryset = self.get_queryset()
                context['total'] = queryset.count()
                context['query'] = query
                context['tittle'] = "Lista de empresas"
                return context
        return context

    def get_queryset(self):
        if self.request.method == "GET":
            query = self.request.GET.get("q")
            if query:
                queryset = Empresa.objects.filter((Q(nombre__icontains = query) | Q (ciudad__nombre__icontains = query)) | Q(cancha__jugadores = query))
                return queryset
        return super().get_queryset()
        
    
    


class DetalleEmpresa(LoginRequiredMixin, DetailView):
    model = Empresa
    template_name = 'detalle-canchas.html'
    #template de la vista
    #Aca se listan las canchas y sus horarios

    def get_context_data(self, *args,  **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['tittle'] = "Empresa: " + self.object.slug
        return context

    def get(self, request, *args, **kwargs):
        try:
            perfil = Empresa.objects.get(nombre= self.get_object().nombre)
        except:
            perfil = None
        if self.request.user.groups.name != 'Cliente' and self.request.user != perfil.encargado.usuario:
            return redirect(reverse('home-next'))
        return super().get(request, *args, **kwargs)
    
    
class DetalleReserva(LoginRequiredMixin, DetailView):
    model = Reserva
    #Toca traer tambien los datos de la cancha.
    template_name = 'detalle-reserva.html'

    def get_context_data(self,  **kwargs):
        context =  super().get_context_data(**kwargs)
        context['hora_final'] = self.object.date + timedelta(hours=1)
        context['tittle'] = "Reserva #: " + str(self.object.pk)
        return context

    def get(self, request, *args, **kwargs):
        ##ESTA VISTA SOLO LA PUEDEN VER LOS DUEÑOS DE LA EMPRESA Y EL USUARIO CLIENTE
        objeto = self.get_object()
        usuario = PerfilCliente.objects.filter(usuario = request.user).first()
        empresario = PerfilEmpresa.objects.filter(usuario = request.user).first()

        if usuario or empresario:
            if (objeto.persona != None and objeto.persona == usuario) or (empresario == objeto.empresa.encargado) or (objeto.persona == None):
                return super().get(request, *args, **kwargs)    
        return(redirect('home-next'))


class VistaAuxReservacion(LoginRequiredMixin, DetailView):
     model = Reserva  

     def get(self, request, *args, **kwargs):
        try: 
            usuario = PerfilCliente.objects.filter(usuario = request.user).first()
        except:
            usuario = None
        if usuario == None:
            return redirect('detalle-reserva', pk = self.get_object().pk) 
        else:
            reserva = Reserva.objects.filter(pk = self.get_object().pk ,persona = usuario).first()
            if reserva:
                if reserva.usuario == usuario:
                    return redirect('detalle-reserva', pk = self.get_object().pk) 
                return redirect('home-next')
            objeto = self.get_object()
            objeto.persona = request.user.perfilcliente
            objeto.estado = 1
            objeto.save()
            return redirect('detalle-reserva', pk = self.get_object().pk) 


#actualizar las canchas
#crear canchas
#lista de reservas
#crear reservas
#actuaizar reservas

#VISTAS EXCLUSIVAS EMPRESA
class UpdateEmpresa(LoginRequiredMixin, UpdateView):
    model = Empresa
    template_name = "update-empresa.html"
    form_class = UpdateEmpresaForm
    #Actualizar datos de la empresa.
    #Aca se veria las Lista de canchas.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            empresa = Empresa.objects.get(encargado = self.request.user.perfilempresa)
        except:
            empresa = None
        context['canchas'] = Cancha.objects.filter(empresa = empresa)
        return context

    def get(self, request, *args, **kwargs):
        try:
            perfil = PerfilEmpresa.objects.get(usuario = request.user)
        except:
            perfil = None
        if perfil:
            return super().get(request, *args, **kwargs)
        return(redirect('home-next'))
    
    

#-------Crear, Actualizar, Eliminar, Listar canchas-----------

class UpdateCanchas(LoginRequiredMixin, UpdateView):
    model = Cancha
    #Aca se actualizan las canchas (Apartado del admin).

class DeleteCanchas(LoginRequiredMixin, DeleteView):
    model = Cancha
    template_name = "eliminar-cancha.html"
    
    def get_success_url(self):
        return reverse_lazy('home-next')

class CrearCanchas(LoginRequiredMixin, CreateView):
    model = Cancha
    form_class = CrearCancha
    template_name = "crear-canchas.html"

    def get_success_url(self):
        return reverse_lazy('home-next')

    def form_valid(self, form):
        cancha = form.save()
        usuario = User.objects.get(username = self.request.user.perfilempresa)
        perfilempresa = PerfilEmpresa.objects.get(usuario = usuario)
        empresa = Empresa.objects.get(encargado = perfilempresa)
        cancha.empresa = empresa
        cancha.save()
        return super().form_valid(form)
class CrearReserva(LoginRequiredMixin, CreateView):
    model = Reserva
    template_name = "crear-reservas.html"
    form_class = CrearReserva

    def get_success_url(self):
        return reverse_lazy('home-next')

    def form_valid(self, form):
        reserva = form.save()
        usuario = User.objects.get(username = self.request.user.perfilempresa)
        perfilempresa = PerfilEmpresa.objects.get(usuario = usuario)
        empresa = Empresa.objects.get(encargado = perfilempresa)
        reserva.empresa = empresa
        reserva.save()
        return super().form_valid(form)

class UpdateReserva(LoginRequiredMixin, UpdateView):
    model = Reserva
    #Aca se actualizan las reservas (Para el admin)

class ListaReservas(LoginRequiredMixin, ListView):
    model = Reserva

#------------------------------------------------------





### VISTAS DE USUARIO CLIENTE

class MisReservaciones(LoginRequiredMixin, DetailView):
    model = PerfilCliente
    template_name = "lista_reserva.html"
    
    def get(self, request, *args, **kwargs):
        if self.request.user != self.get_object().usuario:
            return redirect(reverse('home-view'))
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        perfil = self.get_object()
        if self.request.user == self.get_object().usuario:
            context['reservas'] = Reserva.objects.filter(persona = perfil).order_by('date')
        return context

class VistaConfirmacion(LoginRequiredMixin, DetailView):
    model = Reserva
    #Aca se le diria al usuario que debe confirmar su reserva realizando el pago.
    #Se le da unas opciones de pago.

class ProcesoPago(LoginRequiredMixin, TemplateView):
    #Se agrega la API para realizar el pago (Puede ser una o varia vista dependiendo de las APIS que se usen).
    pass

class VistaReservaConfirmada(LoginRequiredMixin, DetailView):
    model = Reserva
    #Despues de confirmar el pago se le muestra que la reserva ya esta confirmada.

Desarrollo/GolGana/canchas/templates/crear-canchas.html
<form method="POST"> {% csrf_token %}
{{form.as_p}}
<button type="submit">Crear Cancha</button>
</form>

Desarrollo/GolGana/canchas/templates/crear-reservas.html
<form method="POST"> {% csrf_token %}
{{form.as_p}}
<button type="submit">Crear Reserva</button>
</form>

Desarrollo/GolGana/canchas/templates/detalle-reserva.html
{% extends 'GolGana/base.html' %}
{% load static %}
{% load customtags %}

{% block css %}
<link href="{% static 'GolGana/css/detalle-reserva.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
{% include 'GolGana/navegacion-index.html' %}

<section class="detalleReserva">
            
 
  
    <div class="contactCancha row col-12 px-5"> 
        <h4 class="linkhome text-start w-20 mt-4"><a style="text-decoration: none; color:#A4E31D;" href="{% url 'detalle-cancha' reserva.cancha.empresa.slug %}"><i class="fas fa-arrow-left me-2"></i>Regresar</a></h4>
         <hr class="lineaLink">       
        <div class="col-md-7 col-sm-12 text-start mt-4 ">
          <h1>{{reserva.cancha.nombre}}</h1>
          <div class="row col-md-12">
            <img src="{{reserva.cancha.image.url}}" class="imgReserva">
          </div>    
        </div>

        <div class="col-md-5 col-sm-12 text-center my-4">
            <h1 style="color:#f3f4f5!important;">Reserva # {{reserva.pk}}</h1>
            <ul class="list-group">
              <li class="list-group-item descripcionReserva">
                <div class="row">

                  <div class="col-md-6 text-start"><h3>Nombre de la empresa:</h3></div>
                  <div class="col-md-6 text-end"><h4>{{reserva.cancha.empresa.nombre}}</h4></div>

                </div>
                </li>
                <li class="list-group-item descripcionReserva">
                  <div class="row">
  
                    <div class="col-md-6 text-start"><h3>Direccion:</h3></div>
                    <div class="col-md-6 text-end"><h4>{{reserva.cancha.empresa.direccion}}</h4></div>
  
                  </div>
                  </li>
                <li class="list-group-item descripcionReserva">
                <div class="row">

                  <div class="col-md-6 text-start"><h3>Dia:</h3></div>
                  <div class="col-md-6 text-end"><h4>{{reserva.date|date:"D d M, Y"}}</h4></div>

                </div>
                </li>

                <li class="list-group-item descripcionReserva">
                  <div class="row">
  
                    <div class="col-md-6 text-start"><h3>Horario:</h3></div>
                    <div class="col-md-6 text-end"><h4>{{reserva.date.time}} - {{hora_final.time}}</h4></div>
  
                  </div>
                  </li>
                
                  <li class="list-group-item descripcionReserva">
                    <div class="row">
    
                      <div class="col-md-6 text-start"><h3>Nombre de cancha:</h3></div>
                      <div class="col-md-6 text-end"><h4>{{reserva.cancha.nombre}}</h4></div>
    
                    </div>
                    </li>

                    <li class="list-group-item descripcionReserva">
                      <div class="row">
      
                        <div class="col-md-6 text-start"><h3>Tipo de cancha:</h3></div>
                        <div class="col-md-6 text-end"><h4>Futbol {{reserva.cancha.jugadores}}</h4></div>
      
                      </div>
                      </li>

                      <li class="list-group-item descripcionReserva">
                        <div class="row">
        
                          <div class="col-md-6 text-start"><h3>Precio:</h3></div>
                          <div class="col-md-6 text-end"><h4>30.000</h4></div>
        
                        </div>
                        </li>
                        <li class="list-group-item descripcionReserva">
                          <div class="row">
          
                            <div class="col-md-6 text-start"><h3>Estado:</h3></div>
                            <div class="col-md-6 text-end"><h4>{{reserva.get_estado_display}}</h4></div>
          
                          </div>
                          </li>
                        {% if reserva.persona %}
                        <li class="list-group-item descripcionReserva">
                          <div class="row">
          
                            <div class="col-md-6 text-start"><h3>Reservado por:</h3></div>
                            <div class="col-md-6 text-end"><h4>{{reserva.persona.nombre}} {{reserva.persona.apellido}}</h4></div>
          
                          </div>
                          </li>
                        {% endif %}
                <hr class="lineaLink">
                {% if not reserva.persona and not request.user|ver_group:"Empresa" %}
                <a class="btn btn-primary confirmarReserva" href="{% url 'vista-reservacion' reserva.pk %}">Confirmar Reserva</a>
                {% endif %}
              </ul>
        </div>
    </div>

    



</section>

{% include 'GolGana/footer.html' %}
{% endblock %}

Desarrollo/GolGana/canchas/templates/eliminar-cancha.html
<form method="POST">{% csrf_token %}
<p>Esta seguro de borrar {{ object }}</p>
<button type="submit">Borar</button>
</form>

Desarrollo/GolGana/canchas/templates/lista_reserva.html
{% extends 'GolGana/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'GolGana/css/lista_reserva.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% include 'registration/navegacion.html' %}

<section class="lista_reserva row ">
  {% include 'registration/menu-izquierda.html' %}

  <div class="reservas col-xxl-9 col-md-12 col-sm-12">
    <ul class="list-group list-group-flush">
        <h1 class="px-5">Historial</h1>
        <hr class="lineareserva">
    {% for reserva in reservas %}
      <li class="list-group-item container col-md-12">
          <div class="row">
        <div class="imgreserva col-md-4">
            <h2>{{reserva.empresa}}</h2>
            <img src="{{reserva.cancha.image.url}}">
        </div>
        <div class="dtreserva col-md-4">
          <h3 class="mt-4">Dia: {{reserva.date | date:"D, d M Y"}} </h3>
          <h3 class="mt-4">Horario: {{reserva.date | date:"h:i a"}} a {{reserva.get_hora_final | date:"h:i a"}}</h3>
          <h3 class="mt-4">Precio: {{reserva.precio}}</h3>
          <h3 class="mt-4">Estado: {{reserva.get_estado_display}}</h3>
        </div>
        <div class="dtreserva col-md-4">
            <h3 class="mt-4">Dirección: {{reserva.empresa.direccion}}</h3>
            <h3 class="mt-4">Telefono: {{reserva.empresa.telefono}}</h3>
            <h3 class="mt-4"><a class="verreserva btn btn-primary">Ver Reservación</a></h3>

            {% if reserva.estado == 1 %}
            <h3 class="mt-4"><a class="verreserva btn btn-primary">Pagar Reservacion</a></h3>
            {% endif %}
        </div>
    </div>
    <hr class="lineareserva">
     {% endfor %}
    </ul>
  </div>


</section>

{% endblock %}

Desarrollo/GolGana/canchas/templates/update-empresa.html
{% extends 'GolGana/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'GolGana/css/update-empresa.css'%}">

{% endblock %}

{% block content %}

<section class="update-empresa">
    <!--Barras de Navegación--> 
    {% include 'registration/navegacion.html' %}
    <div class="row">
    {% include 'registration/menu-izquierda.html' %}
    
    <div class='formulario-empresa col-md-12 col-xl-9 row d-flex justify-content-center mx-md-0'>
    <form method="POST" action="." id="empresaForm" data-cities-url = "{% url 'ajax_load_cities' %}" class="col-md-12 row">
    {% csrf_token %}
    <h1>Perfil Establecimiento</h1>
    <div class="col-md-6"> 
        
    <div class="mt-2"><h3>Foto Establecimiento</h3><img src="{{form.instance.image.url}}" class="empresaimg"></div>
    <div class="mt-4">
        <h3>Nombre:</h3>
        {{form.nombre}}
    </div>
    </div>
    <div class="col-md-6 row">
        <h3>Descripción</h3>
        {{form.descripcion}}
        <h3 class="mt-1">Teléfono:</h3>
        {{form.telefono}}
        <h3 class="mt-1">Dirección:</h3>
        {{form.direccion}}
        
       
    </div>
    <h3 class="text-center mt-4">Horario de atención</h3>
    <h4 class="col-md-6">Inicio:{{form.hora_inicio}} </h4> <h4 class="col-md-6">Cierre: {{form.hora_final}}</h4>
    <h3><a class="btn btn-primary">Guardar</a></h3>
    </form>

    <!--VER TODAS LAS CANCHAS DE LA EMPRESA--> 
    <div class="canchasreserva col-md-12 container row mt-5">
        <h2>Informacion de canchas</h2>
        {% for cancha in canchas %}
        <div class="col-md-4 m-auto">
        <h3>{{cancha.nombre}}</h3>
        </div>
        <div class="col-md-4 mt-5">
        <img src="{{cancha.image.url}}" class="imgch img-fluid">
        </div>
        <div class="col-md-4 m-auto">
        <a href="#">Editar</a>
        <a href="{% url 'eliminar-cancha' cancha.pk%}">Eliminar</a>
        </div>
        {% endfor %}
        
    <!--HACER LA RESERVA--> 
    {% comment %} <a href="{% url 'crear-reserva' %}">Crear Reserva</a> {% endcomment %}
    
  
    </div>
    </div>     
    </div>

</section>

{% endblock %}


{% block js %}
<script type="text/javascript">
$("#id_departamento").change(function () {
  const url = $("#empresaForm").attr("data-cities-url");  // get the url of the `load_cities` view
  const depId = $(this).val();  // get the selected country ID from the HTML input

  $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
      data: {
          'id_departamento': depId      // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_ciudad").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

});
</script>
{% endblock %}